// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.access-control-admin@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ACCESS_CONTROL_ADMIN_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ACCESS_CONTROL_ADMIN_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_access_control_admin { () => { "{\"capability_id\":\"lenso.access-control-admin@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"assign_role\",\"bootstrap_scope\",\"create_role\",\"delete_role\",\"revoke_role\",\"set_role_permissions\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_access_control_admin_client { () => { "{\"capability_id\":\"lenso.access-control-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_access_control_admin_client { () => { "{\"capability_id\":\"lenso.access-control-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const ASSIGN_ROLE_OPERATION: &str = "assign_role";
pub const BOOTSTRAP_SCOPE_OPERATION: &str = "bootstrap_scope";
pub const CREATE_ROLE_OPERATION: &str = "create_role";
pub const DELETE_ROLE_OPERATION: &str = "delete_role";
pub const REVOKE_ROLE_OPERATION: &str = "revoke_role";
pub const SET_ROLE_PERMISSIONS_OPERATION: &str = "set_role_permissions";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AssignRoleRequest {
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: AssignRoleRequestScope,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AssignRoleRequestScope {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AssignRoleResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AssignRoleError {
    Forbidden,
    InvalidRequest,
    ProtectedBinding,
    ProtectedRole,
    RoleAlreadyExists,
    RoleNotFound,
    ScopeNotBootstrapped,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BootstrapScopeRequest {
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: BootstrapScopeRequestScope,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BootstrapScopeRequestScope {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BootstrapScopeResponse {
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: String,
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum BootstrapScopeError {
    Forbidden,
    InvalidRequest,
    ScopeAlreadyBootstrapped,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateRoleRequest {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: CreateRoleRequestScope,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateRoleRequestScope {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateRoleResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreateRoleError {
    Forbidden,
    InvalidRequest,
    ProtectedBinding,
    ProtectedRole,
    RoleAlreadyExists,
    RoleNotFound,
    ScopeNotBootstrapped,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DeleteRoleRequest {
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: DeleteRoleRequestScope,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DeleteRoleRequestScope {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DeleteRoleResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DeleteRoleError {
    Forbidden,
    InvalidRequest,
    ProtectedBinding,
    ProtectedRole,
    RoleAlreadyExists,
    RoleNotFound,
    ScopeNotBootstrapped,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeRoleRequest {
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: RevokeRoleRequestScope,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeRoleRequestScope {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeRoleResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RevokeRoleError {
    Forbidden,
    InvalidRequest,
    ProtectedBinding,
    ProtectedRole,
    RoleAlreadyExists,
    RoleNotFound,
    ScopeNotBootstrapped,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SetRolePermissionsRequest {
    #[serde(rename = "permissions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub permissions: Vec<String>,
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: SetRolePermissionsRequestScope,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SetRolePermissionsRequestScope {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SetRolePermissionsResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SetRolePermissionsError {
    Forbidden,
    InvalidRequest,
    ProtectedBinding,
    ProtectedRole,
    RoleAlreadyExists,
    RoleNotFound,
    ScopeNotBootstrapped,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct AccessControlAdminAssignRole;
impl RequestCapability for AccessControlAdminAssignRole {
    type Request = AssignRoleRequest;
    type Response = AssignRoleResponse;
    type DomainError = AssignRoleError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ASSIGN_ROLE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccessControlAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).assign_role(context, request)
    }
}

#[derive(Debug)]
pub struct AccessControlAdminBootstrapScope;
impl RequestCapability for AccessControlAdminBootstrapScope {
    type Request = BootstrapScopeRequest;
    type Response = BootstrapScopeResponse;
    type DomainError = BootstrapScopeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != BOOTSTRAP_SCOPE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccessControlAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).bootstrap_scope(context, request)
    }
}

#[derive(Debug)]
pub struct AccessControlAdminCreateRole;
impl RequestCapability for AccessControlAdminCreateRole {
    type Request = CreateRoleRequest;
    type Response = CreateRoleResponse;
    type DomainError = CreateRoleError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_ROLE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccessControlAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create_role(context, request)
    }
}

#[derive(Debug)]
pub struct AccessControlAdminDeleteRole;
impl RequestCapability for AccessControlAdminDeleteRole {
    type Request = DeleteRoleRequest;
    type Response = DeleteRoleResponse;
    type DomainError = DeleteRoleError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DELETE_ROLE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccessControlAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).delete_role(context, request)
    }
}

#[derive(Debug)]
pub struct AccessControlAdminRevokeRole;
impl RequestCapability for AccessControlAdminRevokeRole {
    type Request = RevokeRoleRequest;
    type Response = RevokeRoleResponse;
    type DomainError = RevokeRoleError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REVOKE_ROLE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccessControlAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).revoke_role(context, request)
    }
}

#[derive(Debug)]
pub struct AccessControlAdminSetRolePermissions;
impl RequestCapability for AccessControlAdminSetRolePermissions {
    type Request = SetRolePermissionsRequest;
    type Response = SetRolePermissionsResponse;
    type DomainError = SetRolePermissionsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SET_ROLE_PERMISSIONS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccessControlAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).set_role_permissions(context, request)
    }
}

impl serde::Serialize for AssignRoleError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::ProtectedBinding => serializer.serialize_str("protected_binding"),
            Self::ProtectedRole => serializer.serialize_str("protected_role"),
            Self::RoleAlreadyExists => serializer.serialize_str("role_already_exists"),
            Self::RoleNotFound => serializer.serialize_str("role_not_found"),
            Self::ScopeNotBootstrapped => serializer.serialize_str("scope_not_bootstrapped"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AssignRoleError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "protected_binding" => Ok(Self::ProtectedBinding),
                "protected_role" => Ok(Self::ProtectedRole),
                "role_already_exists" => Ok(Self::RoleAlreadyExists),
                "role_not_found" => Ok(Self::RoleNotFound),
                "scope_not_bootstrapped" => Ok(Self::ScopeNotBootstrapped),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for BootstrapScopeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::ScopeAlreadyBootstrapped => serializer.serialize_str("scope_already_bootstrapped"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for BootstrapScopeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "scope_already_bootstrapped" => Ok(Self::ScopeAlreadyBootstrapped),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for CreateRoleError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::ProtectedBinding => serializer.serialize_str("protected_binding"),
            Self::ProtectedRole => serializer.serialize_str("protected_role"),
            Self::RoleAlreadyExists => serializer.serialize_str("role_already_exists"),
            Self::RoleNotFound => serializer.serialize_str("role_not_found"),
            Self::ScopeNotBootstrapped => serializer.serialize_str("scope_not_bootstrapped"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreateRoleError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "protected_binding" => Ok(Self::ProtectedBinding),
                "protected_role" => Ok(Self::ProtectedRole),
                "role_already_exists" => Ok(Self::RoleAlreadyExists),
                "role_not_found" => Ok(Self::RoleNotFound),
                "scope_not_bootstrapped" => Ok(Self::ScopeNotBootstrapped),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for DeleteRoleError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::ProtectedBinding => serializer.serialize_str("protected_binding"),
            Self::ProtectedRole => serializer.serialize_str("protected_role"),
            Self::RoleAlreadyExists => serializer.serialize_str("role_already_exists"),
            Self::RoleNotFound => serializer.serialize_str("role_not_found"),
            Self::ScopeNotBootstrapped => serializer.serialize_str("scope_not_bootstrapped"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DeleteRoleError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "protected_binding" => Ok(Self::ProtectedBinding),
                "protected_role" => Ok(Self::ProtectedRole),
                "role_already_exists" => Ok(Self::RoleAlreadyExists),
                "role_not_found" => Ok(Self::RoleNotFound),
                "scope_not_bootstrapped" => Ok(Self::ScopeNotBootstrapped),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RevokeRoleError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::ProtectedBinding => serializer.serialize_str("protected_binding"),
            Self::ProtectedRole => serializer.serialize_str("protected_role"),
            Self::RoleAlreadyExists => serializer.serialize_str("role_already_exists"),
            Self::RoleNotFound => serializer.serialize_str("role_not_found"),
            Self::ScopeNotBootstrapped => serializer.serialize_str("scope_not_bootstrapped"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RevokeRoleError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "protected_binding" => Ok(Self::ProtectedBinding),
                "protected_role" => Ok(Self::ProtectedRole),
                "role_already_exists" => Ok(Self::RoleAlreadyExists),
                "role_not_found" => Ok(Self::RoleNotFound),
                "scope_not_bootstrapped" => Ok(Self::ScopeNotBootstrapped),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for SetRolePermissionsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::ProtectedBinding => serializer.serialize_str("protected_binding"),
            Self::ProtectedRole => serializer.serialize_str("protected_role"),
            Self::RoleAlreadyExists => serializer.serialize_str("role_already_exists"),
            Self::RoleNotFound => serializer.serialize_str("role_not_found"),
            Self::ScopeNotBootstrapped => serializer.serialize_str("scope_not_bootstrapped"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SetRolePermissionsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "protected_binding" => Ok(Self::ProtectedBinding),
                "protected_role" => Ok(Self::ProtectedRole),
                "role_already_exists" => Ok(Self::RoleAlreadyExists),
                "role_not_found" => Ok(Self::RoleNotFound),
                "scope_not_bootstrapped" => Ok(Self::ScopeNotBootstrapped),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_assign_role_request(value: &AssignRoleRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_assign_role_request(wire: &str) -> Result<AssignRoleRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_assign_role_response(value: &AssignRoleResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_assign_role_response(wire: &str) -> Result<AssignRoleResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_assign_role_error(value: &AssignRoleError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_assign_role_error(wire: &str) -> Result<AssignRoleError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_bootstrap_scope_request(value: &BootstrapScopeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_bootstrap_scope_request(wire: &str) -> Result<BootstrapScopeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_bootstrap_scope_response(value: &BootstrapScopeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_bootstrap_scope_response(wire: &str) -> Result<BootstrapScopeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_bootstrap_scope_error(value: &BootstrapScopeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_bootstrap_scope_error(wire: &str) -> Result<BootstrapScopeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_create_role_request(value: &CreateRoleRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_role_request(wire: &str) -> Result<CreateRoleRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_role_response(value: &CreateRoleResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_role_response(wire: &str) -> Result<CreateRoleResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_role_error(value: &CreateRoleError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_role_error(wire: &str) -> Result<CreateRoleError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_delete_role_request(value: &DeleteRoleRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_delete_role_request(wire: &str) -> Result<DeleteRoleRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_delete_role_response(value: &DeleteRoleResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_delete_role_response(wire: &str) -> Result<DeleteRoleResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_delete_role_error(value: &DeleteRoleError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_delete_role_error(wire: &str) -> Result<DeleteRoleError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_revoke_role_request(value: &RevokeRoleRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_role_request(wire: &str) -> Result<RevokeRoleRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_role_response(value: &RevokeRoleResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_role_response(wire: &str) -> Result<RevokeRoleResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_role_error(value: &RevokeRoleError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_role_error(wire: &str) -> Result<RevokeRoleError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_set_role_permissions_request(value: &SetRolePermissionsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_role_permissions_request(wire: &str) -> Result<SetRolePermissionsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_set_role_permissions_response(value: &SetRolePermissionsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_role_permissions_response(wire: &str) -> Result<SetRolePermissionsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_set_role_permissions_error(value: &SetRolePermissionsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_role_permissions_error(wire: &str) -> Result<SetRolePermissionsError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoAccessControlAdminAssignRoleResult {
    fn __lenso_into_result(self) -> Result<Result<AssignRoleResponse, AssignRoleError>, RuntimeFailure>;
}
impl __LensoIntoAccessControlAdminAssignRoleResult for Result<AssignRoleResponse, AssignRoleError> {
    fn __lenso_into_result(self) -> Result<Result<AssignRoleResponse, AssignRoleError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccessControlAdminAssignRoleResult for Result<Result<AssignRoleResponse, AssignRoleError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AssignRoleResponse, AssignRoleError>, RuntimeFailure> { self }
}
impl __LensoIntoAccessControlAdminAssignRoleResult for Result<AssignRoleResponse, lenso_plugin_authoring::PluginError<AssignRoleError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AssignRoleResponse, AssignRoleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccessControlAdminAssignRoleResult for Result<AssignRoleResponse, AccessControlAdminAssignRoleInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AssignRoleResponse, AssignRoleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccessControlAdminAssignRoleInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccessControlAdminAssignRoleInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAccessControlAdminBootstrapScopeResult {
    fn __lenso_into_result(self) -> Result<Result<BootstrapScopeResponse, BootstrapScopeError>, RuntimeFailure>;
}
impl __LensoIntoAccessControlAdminBootstrapScopeResult for Result<BootstrapScopeResponse, BootstrapScopeError> {
    fn __lenso_into_result(self) -> Result<Result<BootstrapScopeResponse, BootstrapScopeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccessControlAdminBootstrapScopeResult for Result<Result<BootstrapScopeResponse, BootstrapScopeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<BootstrapScopeResponse, BootstrapScopeError>, RuntimeFailure> { self }
}
impl __LensoIntoAccessControlAdminBootstrapScopeResult for Result<BootstrapScopeResponse, lenso_plugin_authoring::PluginError<BootstrapScopeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<BootstrapScopeResponse, BootstrapScopeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccessControlAdminBootstrapScopeResult for Result<BootstrapScopeResponse, AccessControlAdminBootstrapScopeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<BootstrapScopeResponse, BootstrapScopeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccessControlAdminBootstrapScopeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccessControlAdminBootstrapScopeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAccessControlAdminCreateRoleResult {
    fn __lenso_into_result(self) -> Result<Result<CreateRoleResponse, CreateRoleError>, RuntimeFailure>;
}
impl __LensoIntoAccessControlAdminCreateRoleResult for Result<CreateRoleResponse, CreateRoleError> {
    fn __lenso_into_result(self) -> Result<Result<CreateRoleResponse, CreateRoleError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccessControlAdminCreateRoleResult for Result<Result<CreateRoleResponse, CreateRoleError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreateRoleResponse, CreateRoleError>, RuntimeFailure> { self }
}
impl __LensoIntoAccessControlAdminCreateRoleResult for Result<CreateRoleResponse, lenso_plugin_authoring::PluginError<CreateRoleError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreateRoleResponse, CreateRoleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccessControlAdminCreateRoleResult for Result<CreateRoleResponse, AccessControlAdminCreateRoleInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreateRoleResponse, CreateRoleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccessControlAdminCreateRoleInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccessControlAdminCreateRoleInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAccessControlAdminDeleteRoleResult {
    fn __lenso_into_result(self) -> Result<Result<DeleteRoleResponse, DeleteRoleError>, RuntimeFailure>;
}
impl __LensoIntoAccessControlAdminDeleteRoleResult for Result<DeleteRoleResponse, DeleteRoleError> {
    fn __lenso_into_result(self) -> Result<Result<DeleteRoleResponse, DeleteRoleError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccessControlAdminDeleteRoleResult for Result<Result<DeleteRoleResponse, DeleteRoleError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DeleteRoleResponse, DeleteRoleError>, RuntimeFailure> { self }
}
impl __LensoIntoAccessControlAdminDeleteRoleResult for Result<DeleteRoleResponse, lenso_plugin_authoring::PluginError<DeleteRoleError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DeleteRoleResponse, DeleteRoleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccessControlAdminDeleteRoleResult for Result<DeleteRoleResponse, AccessControlAdminDeleteRoleInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DeleteRoleResponse, DeleteRoleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccessControlAdminDeleteRoleInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccessControlAdminDeleteRoleInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAccessControlAdminRevokeRoleResult {
    fn __lenso_into_result(self) -> Result<Result<RevokeRoleResponse, RevokeRoleError>, RuntimeFailure>;
}
impl __LensoIntoAccessControlAdminRevokeRoleResult for Result<RevokeRoleResponse, RevokeRoleError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeRoleResponse, RevokeRoleError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccessControlAdminRevokeRoleResult for Result<Result<RevokeRoleResponse, RevokeRoleError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RevokeRoleResponse, RevokeRoleError>, RuntimeFailure> { self }
}
impl __LensoIntoAccessControlAdminRevokeRoleResult for Result<RevokeRoleResponse, lenso_plugin_authoring::PluginError<RevokeRoleError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RevokeRoleResponse, RevokeRoleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccessControlAdminRevokeRoleResult for Result<RevokeRoleResponse, AccessControlAdminRevokeRoleInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeRoleResponse, RevokeRoleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccessControlAdminRevokeRoleInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccessControlAdminRevokeRoleInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAccessControlAdminSetRolePermissionsResult {
    fn __lenso_into_result(self) -> Result<Result<SetRolePermissionsResponse, SetRolePermissionsError>, RuntimeFailure>;
}
impl __LensoIntoAccessControlAdminSetRolePermissionsResult for Result<SetRolePermissionsResponse, SetRolePermissionsError> {
    fn __lenso_into_result(self) -> Result<Result<SetRolePermissionsResponse, SetRolePermissionsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccessControlAdminSetRolePermissionsResult for Result<Result<SetRolePermissionsResponse, SetRolePermissionsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SetRolePermissionsResponse, SetRolePermissionsError>, RuntimeFailure> { self }
}
impl __LensoIntoAccessControlAdminSetRolePermissionsResult for Result<SetRolePermissionsResponse, lenso_plugin_authoring::PluginError<SetRolePermissionsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SetRolePermissionsResponse, SetRolePermissionsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccessControlAdminSetRolePermissionsResult for Result<SetRolePermissionsResponse, AccessControlAdminSetRolePermissionsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SetRolePermissionsResponse, SetRolePermissionsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccessControlAdminSetRolePermissionsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccessControlAdminSetRolePermissionsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait AccessControlAdminProvider: fmt::Debug + 'static {
    fn assign_role(&self, context: InvocationContext, request: AssignRoleRequest) -> NativeRequestFuture<AccessControlAdminAssignRole>;
    fn bootstrap_scope(&self, context: InvocationContext, request: BootstrapScopeRequest) -> NativeRequestFuture<AccessControlAdminBootstrapScope>;
    fn create_role(&self, context: InvocationContext, request: CreateRoleRequest) -> NativeRequestFuture<AccessControlAdminCreateRole>;
    fn delete_role(&self, context: InvocationContext, request: DeleteRoleRequest) -> NativeRequestFuture<AccessControlAdminDeleteRole>;
    fn revoke_role(&self, context: InvocationContext, request: RevokeRoleRequest) -> NativeRequestFuture<AccessControlAdminRevokeRole>;
    fn set_role_permissions(&self, context: InvocationContext, request: SetRolePermissionsRequest) -> NativeRequestFuture<AccessControlAdminSetRolePermissions>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_access_control_admin {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportAccessControlAdmin;
        impl $crate::AccessControlAdminProvider for $plugin {
        fn assign_role(&self, context: __LensoNativeSupportAccessControlAdmin::InvocationContext, request: $crate::AssignRoleRequest) -> __LensoNativeSupportAccessControlAdmin::NativeRequestFuture<$crate::AccessControlAdminAssignRole> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::assign_role(&plugin, context, request).await;
                $crate::__LensoIntoAccessControlAdminAssignRoleResult::__lenso_into_result(result)
            })
        }
        fn bootstrap_scope(&self, context: __LensoNativeSupportAccessControlAdmin::InvocationContext, request: $crate::BootstrapScopeRequest) -> __LensoNativeSupportAccessControlAdmin::NativeRequestFuture<$crate::AccessControlAdminBootstrapScope> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::bootstrap_scope(&plugin, context, request).await;
                $crate::__LensoIntoAccessControlAdminBootstrapScopeResult::__lenso_into_result(result)
            })
        }
        fn create_role(&self, context: __LensoNativeSupportAccessControlAdmin::InvocationContext, request: $crate::CreateRoleRequest) -> __LensoNativeSupportAccessControlAdmin::NativeRequestFuture<$crate::AccessControlAdminCreateRole> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create_role(&plugin, context, request).await;
                $crate::__LensoIntoAccessControlAdminCreateRoleResult::__lenso_into_result(result)
            })
        }
        fn delete_role(&self, context: __LensoNativeSupportAccessControlAdmin::InvocationContext, request: $crate::DeleteRoleRequest) -> __LensoNativeSupportAccessControlAdmin::NativeRequestFuture<$crate::AccessControlAdminDeleteRole> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::delete_role(&plugin, context, request).await;
                $crate::__LensoIntoAccessControlAdminDeleteRoleResult::__lenso_into_result(result)
            })
        }
        fn revoke_role(&self, context: __LensoNativeSupportAccessControlAdmin::InvocationContext, request: $crate::RevokeRoleRequest) -> __LensoNativeSupportAccessControlAdmin::NativeRequestFuture<$crate::AccessControlAdminRevokeRole> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::revoke_role(&plugin, context, request).await;
                $crate::__LensoIntoAccessControlAdminRevokeRoleResult::__lenso_into_result(result)
            })
        }
        fn set_role_permissions(&self, context: __LensoNativeSupportAccessControlAdmin::InvocationContext, request: $crate::SetRolePermissionsRequest) -> __LensoNativeSupportAccessControlAdmin::NativeRequestFuture<$crate::AccessControlAdminSetRolePermissions> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::set_role_permissions(&plugin, context, request).await;
                $crate::__LensoIntoAccessControlAdminSetRolePermissionsResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct AccessControlAdminRequestEndpoint { provider: Rc<dyn AccessControlAdminProvider> }

#[derive(Debug)]
pub struct AccessControlAdminEndpoint<P: AccessControlAdminProvider> { provider: Rc<P>, request_endpoint: AccessControlAdminRequestEndpoint }
impl<P: AccessControlAdminProvider> AccessControlAdminEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn AccessControlAdminProvider> = provider.clone();
        Self { provider, request_endpoint: AccessControlAdminRequestEndpoint { provider: request_provider } }
    }
}

impl<P: AccessControlAdminProvider> NativeRequestEndpoint for AccessControlAdminEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ASSIGN_ROLE_OPERATION,
        BOOTSTRAP_SCOPE_OPERATION,
        CREATE_ROLE_OPERATION,
        DELETE_ROLE_OPERATION,
        REVOKE_ROLE_OPERATION,
        SET_ROLE_PERMISSIONS_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ASSIGN_ROLE_OPERATION => {
                let Ok(request) = request.downcast::<AssignRoleRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).assign_role(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            BOOTSTRAP_SCOPE_OPERATION => {
                let Ok(request) = request.downcast::<BootstrapScopeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).bootstrap_scope(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            CREATE_ROLE_OPERATION => {
                let Ok(request) = request.downcast::<CreateRoleRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create_role(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            DELETE_ROLE_OPERATION => {
                let Ok(request) = request.downcast::<DeleteRoleRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).delete_role(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REVOKE_ROLE_OPERATION => {
                let Ok(request) = request.downcast::<RevokeRoleRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).revoke_role(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            SET_ROLE_PERMISSIONS_OPERATION => {
                let Ok(request) = request.downcast::<SetRolePermissionsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).set_role_permissions(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_access_control_admin {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::AccessControlAdminEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_access_control_admin {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_access_control_admin!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct AccessControlAdminClient {
    assign_role: NativeRequestHandle<AccessControlAdminAssignRole>,
    bootstrap_scope: NativeRequestHandle<AccessControlAdminBootstrapScope>,
    create_role: NativeRequestHandle<AccessControlAdminCreateRole>,
    delete_role: NativeRequestHandle<AccessControlAdminDeleteRole>,
    revoke_role: NativeRequestHandle<AccessControlAdminRevokeRole>,
    set_role_permissions: NativeRequestHandle<AccessControlAdminSetRolePermissions>,
}
impl AccessControlAdminClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn assign_role(&self, request: AssignRoleRequest) -> Result<AssignRoleResponse, AccessControlAdminAssignRoleInvocationError> {
        self.assign_role.invoke(ASSIGN_ROLE_OPERATION, request).await
            .map_err(AccessControlAdminAssignRoleInvocationError::Runtime)?
            .map_err(AccessControlAdminAssignRoleInvocationError::Domain)
    }

    pub async fn assign_role_with_context(&self, context: InvocationContext, request: AssignRoleRequest) -> Result<AssignRoleResponse, AccessControlAdminAssignRoleInvocationError> {
        self.assign_role.invoke_with_context(ASSIGN_ROLE_OPERATION, context, request).await
            .map_err(AccessControlAdminAssignRoleInvocationError::Runtime)?
            .map_err(AccessControlAdminAssignRoleInvocationError::Domain)
    }

    pub async fn bootstrap_scope(&self, request: BootstrapScopeRequest) -> Result<BootstrapScopeResponse, AccessControlAdminBootstrapScopeInvocationError> {
        self.bootstrap_scope.invoke(BOOTSTRAP_SCOPE_OPERATION, request).await
            .map_err(AccessControlAdminBootstrapScopeInvocationError::Runtime)?
            .map_err(AccessControlAdminBootstrapScopeInvocationError::Domain)
    }

    pub async fn bootstrap_scope_with_context(&self, context: InvocationContext, request: BootstrapScopeRequest) -> Result<BootstrapScopeResponse, AccessControlAdminBootstrapScopeInvocationError> {
        self.bootstrap_scope.invoke_with_context(BOOTSTRAP_SCOPE_OPERATION, context, request).await
            .map_err(AccessControlAdminBootstrapScopeInvocationError::Runtime)?
            .map_err(AccessControlAdminBootstrapScopeInvocationError::Domain)
    }

    pub async fn create_role(&self, request: CreateRoleRequest) -> Result<CreateRoleResponse, AccessControlAdminCreateRoleInvocationError> {
        self.create_role.invoke(CREATE_ROLE_OPERATION, request).await
            .map_err(AccessControlAdminCreateRoleInvocationError::Runtime)?
            .map_err(AccessControlAdminCreateRoleInvocationError::Domain)
    }

    pub async fn create_role_with_context(&self, context: InvocationContext, request: CreateRoleRequest) -> Result<CreateRoleResponse, AccessControlAdminCreateRoleInvocationError> {
        self.create_role.invoke_with_context(CREATE_ROLE_OPERATION, context, request).await
            .map_err(AccessControlAdminCreateRoleInvocationError::Runtime)?
            .map_err(AccessControlAdminCreateRoleInvocationError::Domain)
    }

    pub async fn delete_role(&self, request: DeleteRoleRequest) -> Result<DeleteRoleResponse, AccessControlAdminDeleteRoleInvocationError> {
        self.delete_role.invoke(DELETE_ROLE_OPERATION, request).await
            .map_err(AccessControlAdminDeleteRoleInvocationError::Runtime)?
            .map_err(AccessControlAdminDeleteRoleInvocationError::Domain)
    }

    pub async fn delete_role_with_context(&self, context: InvocationContext, request: DeleteRoleRequest) -> Result<DeleteRoleResponse, AccessControlAdminDeleteRoleInvocationError> {
        self.delete_role.invoke_with_context(DELETE_ROLE_OPERATION, context, request).await
            .map_err(AccessControlAdminDeleteRoleInvocationError::Runtime)?
            .map_err(AccessControlAdminDeleteRoleInvocationError::Domain)
    }

    pub async fn revoke_role(&self, request: RevokeRoleRequest) -> Result<RevokeRoleResponse, AccessControlAdminRevokeRoleInvocationError> {
        self.revoke_role.invoke(REVOKE_ROLE_OPERATION, request).await
            .map_err(AccessControlAdminRevokeRoleInvocationError::Runtime)?
            .map_err(AccessControlAdminRevokeRoleInvocationError::Domain)
    }

    pub async fn revoke_role_with_context(&self, context: InvocationContext, request: RevokeRoleRequest) -> Result<RevokeRoleResponse, AccessControlAdminRevokeRoleInvocationError> {
        self.revoke_role.invoke_with_context(REVOKE_ROLE_OPERATION, context, request).await
            .map_err(AccessControlAdminRevokeRoleInvocationError::Runtime)?
            .map_err(AccessControlAdminRevokeRoleInvocationError::Domain)
    }

    pub async fn set_role_permissions(&self, request: SetRolePermissionsRequest) -> Result<SetRolePermissionsResponse, AccessControlAdminSetRolePermissionsInvocationError> {
        self.set_role_permissions.invoke(SET_ROLE_PERMISSIONS_OPERATION, request).await
            .map_err(AccessControlAdminSetRolePermissionsInvocationError::Runtime)?
            .map_err(AccessControlAdminSetRolePermissionsInvocationError::Domain)
    }

    pub async fn set_role_permissions_with_context(&self, context: InvocationContext, request: SetRolePermissionsRequest) -> Result<SetRolePermissionsResponse, AccessControlAdminSetRolePermissionsInvocationError> {
        self.set_role_permissions.invoke_with_context(SET_ROLE_PERMISSIONS_OPERATION, context, request).await
            .map_err(AccessControlAdminSetRolePermissionsInvocationError::Runtime)?
            .map_err(AccessControlAdminSetRolePermissionsInvocationError::Domain)
    }
}

impl CapabilityClient for AccessControlAdminClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            assign_role: dependencies.one::<AccessControlAdminAssignRole>()?,
            bootstrap_scope: dependencies.one::<AccessControlAdminBootstrapScope>()?,
            create_role: dependencies.one::<AccessControlAdminCreateRole>()?,
            delete_role: dependencies.one::<AccessControlAdminDeleteRole>()?,
            revoke_role: dependencies.one::<AccessControlAdminRevokeRole>()?,
            set_role_permissions: dependencies.one::<AccessControlAdminSetRolePermissions>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for AccessControlAdminClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    assign_role: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccessControlAdminAssignRole>()?,
                    bootstrap_scope: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccessControlAdminBootstrapScope>()?,
                    create_role: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccessControlAdminCreateRole>()?,
                    delete_role: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccessControlAdminDeleteRole>()?,
                    revoke_role: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccessControlAdminRevokeRole>()?,
                    set_role_permissions: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccessControlAdminSetRolePermissions>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum AccessControlAdminAssignRoleInvocationError {
    Domain(AssignRoleError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AccessControlAdminBootstrapScopeInvocationError {
    Domain(BootstrapScopeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AccessControlAdminCreateRoleInvocationError {
    Domain(CreateRoleError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AccessControlAdminDeleteRoleInvocationError {
    Domain(DeleteRoleError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AccessControlAdminRevokeRoleInvocationError {
    Domain(RevokeRoleError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AccessControlAdminSetRolePermissionsInvocationError {
    Domain(SetRolePermissionsError),
    Runtime(RuntimeFailure),
}
