// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.access-control-directory@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ACCESS_CONTROL_DIRECTORY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ACCESS_CONTROL_DIRECTORY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_access_control_directory { () => { "{\"capability_id\":\"lenso.access-control-directory@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"get_role\",\"list_roles\",\"list_subject_roles\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_access_control_directory_client { () => { "{\"capability_id\":\"lenso.access-control-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_access_control_directory_client { () => { "{\"capability_id\":\"lenso.access-control-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const GET_ROLE_OPERATION: &str = "get_role";
pub const LIST_ROLES_OPERATION: &str = "list_roles";
pub const LIST_SUBJECT_ROLES_OPERATION: &str = "list_subject_roles";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRoleRequest {
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: Scope,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Scope {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRoleResponse {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "permissions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub permissions: Vec<String>,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: String,
    #[serde(rename = "protected")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub protected: bool,
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetRoleError {
    Forbidden,
    InvalidRequest,
    RoleNotFound,
    ScopeNotBootstrapped,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRolesRequest {
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: Scope,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRolesResponse {
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: String,
    #[serde(rename = "roles")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub roles: Vec<Role>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Role {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "permissions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub permissions: Vec<String>,
    #[serde(rename = "protected")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub protected: bool,
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListRolesError {
    Forbidden,
    InvalidPage,
    InvalidRequest,
    ScopeNotBootstrapped,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListSubjectRolesRequest {
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: Scope,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListSubjectRolesResponse {
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: String,
    #[serde(rename = "roles")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub roles: Vec<Role>,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListSubjectRolesError {
    Forbidden,
    InvalidPage,
    InvalidRequest,
    ScopeNotBootstrapped,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct AccessControlDirectoryGetRole;
impl RequestCapability for AccessControlDirectoryGetRole {
    type Request = GetRoleRequest;
    type Response = GetRoleResponse;
    type DomainError = GetRoleError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_ROLE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccessControlDirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_role(context, request)
    }
}

#[derive(Debug)]
pub struct AccessControlDirectoryListRoles;
impl RequestCapability for AccessControlDirectoryListRoles {
    type Request = ListRolesRequest;
    type Response = ListRolesResponse;
    type DomainError = ListRolesError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_ROLES_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccessControlDirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_roles(context, request)
    }
}

#[derive(Debug)]
pub struct AccessControlDirectoryListSubjectRoles;
impl RequestCapability for AccessControlDirectoryListSubjectRoles {
    type Request = ListSubjectRolesRequest;
    type Response = ListSubjectRolesResponse;
    type DomainError = ListSubjectRolesError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_SUBJECT_ROLES_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AccessControlDirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_subject_roles(context, request)
    }
}

impl serde::Serialize for GetRoleError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::RoleNotFound => serializer.serialize_str("role_not_found"),
            Self::ScopeNotBootstrapped => serializer.serialize_str("scope_not_bootstrapped"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetRoleError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "role_not_found" => Ok(Self::RoleNotFound),
                "scope_not_bootstrapped" => Ok(Self::ScopeNotBootstrapped),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListRolesError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidPage => serializer.serialize_str("invalid_page"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::ScopeNotBootstrapped => serializer.serialize_str("scope_not_bootstrapped"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListRolesError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_page" => Ok(Self::InvalidPage),
                "invalid_request" => Ok(Self::InvalidRequest),
                "scope_not_bootstrapped" => Ok(Self::ScopeNotBootstrapped),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListSubjectRolesError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidPage => serializer.serialize_str("invalid_page"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::ScopeNotBootstrapped => serializer.serialize_str("scope_not_bootstrapped"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListSubjectRolesError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_page" => Ok(Self::InvalidPage),
                "invalid_request" => Ok(Self::InvalidRequest),
                "scope_not_bootstrapped" => Ok(Self::ScopeNotBootstrapped),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_get_role_request(value: &GetRoleRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_role_request(wire: &str) -> Result<GetRoleRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_role_response(value: &GetRoleResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_role_response(wire: &str) -> Result<GetRoleResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_role_error(value: &GetRoleError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_role_error(wire: &str) -> Result<GetRoleError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_roles_request(value: &ListRolesRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_roles_request(wire: &str) -> Result<ListRolesRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_roles_response(value: &ListRolesResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_roles_response(wire: &str) -> Result<ListRolesResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_roles_error(value: &ListRolesError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_roles_error(wire: &str) -> Result<ListRolesError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_subject_roles_request(value: &ListSubjectRolesRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_subject_roles_request(wire: &str) -> Result<ListSubjectRolesRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_subject_roles_response(value: &ListSubjectRolesResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_subject_roles_response(wire: &str) -> Result<ListSubjectRolesResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_subject_roles_error(value: &ListSubjectRolesError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_subject_roles_error(wire: &str) -> Result<ListSubjectRolesError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoAccessControlDirectoryGetRoleResult {
    fn __lenso_into_result(self) -> Result<Result<GetRoleResponse, GetRoleError>, RuntimeFailure>;
}
impl __LensoIntoAccessControlDirectoryGetRoleResult for Result<GetRoleResponse, GetRoleError> {
    fn __lenso_into_result(self) -> Result<Result<GetRoleResponse, GetRoleError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccessControlDirectoryGetRoleResult for Result<Result<GetRoleResponse, GetRoleError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetRoleResponse, GetRoleError>, RuntimeFailure> { self }
}
impl __LensoIntoAccessControlDirectoryGetRoleResult for Result<GetRoleResponse, lenso_plugin_authoring::PluginError<GetRoleError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetRoleResponse, GetRoleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccessControlDirectoryGetRoleResult for Result<GetRoleResponse, AccessControlDirectoryGetRoleInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetRoleResponse, GetRoleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccessControlDirectoryGetRoleInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccessControlDirectoryGetRoleInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAccessControlDirectoryListRolesResult {
    fn __lenso_into_result(self) -> Result<Result<ListRolesResponse, ListRolesError>, RuntimeFailure>;
}
impl __LensoIntoAccessControlDirectoryListRolesResult for Result<ListRolesResponse, ListRolesError> {
    fn __lenso_into_result(self) -> Result<Result<ListRolesResponse, ListRolesError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccessControlDirectoryListRolesResult for Result<Result<ListRolesResponse, ListRolesError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListRolesResponse, ListRolesError>, RuntimeFailure> { self }
}
impl __LensoIntoAccessControlDirectoryListRolesResult for Result<ListRolesResponse, lenso_plugin_authoring::PluginError<ListRolesError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListRolesResponse, ListRolesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccessControlDirectoryListRolesResult for Result<ListRolesResponse, AccessControlDirectoryListRolesInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListRolesResponse, ListRolesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccessControlDirectoryListRolesInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccessControlDirectoryListRolesInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAccessControlDirectoryListSubjectRolesResult {
    fn __lenso_into_result(self) -> Result<Result<ListSubjectRolesResponse, ListSubjectRolesError>, RuntimeFailure>;
}
impl __LensoIntoAccessControlDirectoryListSubjectRolesResult for Result<ListSubjectRolesResponse, ListSubjectRolesError> {
    fn __lenso_into_result(self) -> Result<Result<ListSubjectRolesResponse, ListSubjectRolesError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAccessControlDirectoryListSubjectRolesResult for Result<Result<ListSubjectRolesResponse, ListSubjectRolesError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListSubjectRolesResponse, ListSubjectRolesError>, RuntimeFailure> { self }
}
impl __LensoIntoAccessControlDirectoryListSubjectRolesResult for Result<ListSubjectRolesResponse, lenso_plugin_authoring::PluginError<ListSubjectRolesError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListSubjectRolesResponse, ListSubjectRolesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAccessControlDirectoryListSubjectRolesResult for Result<ListSubjectRolesResponse, AccessControlDirectoryListSubjectRolesInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListSubjectRolesResponse, ListSubjectRolesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AccessControlDirectoryListSubjectRolesInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AccessControlDirectoryListSubjectRolesInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait AccessControlDirectoryProvider: fmt::Debug + 'static {
    fn get_role(&self, context: InvocationContext, request: GetRoleRequest) -> NativeRequestFuture<AccessControlDirectoryGetRole>;
    fn list_roles(&self, context: InvocationContext, request: ListRolesRequest) -> NativeRequestFuture<AccessControlDirectoryListRoles>;
    fn list_subject_roles(&self, context: InvocationContext, request: ListSubjectRolesRequest) -> NativeRequestFuture<AccessControlDirectoryListSubjectRoles>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_access_control_directory {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportAccessControlDirectory;
        impl $crate::AccessControlDirectoryProvider for $plugin {
        fn get_role(&self, context: __LensoNativeSupportAccessControlDirectory::InvocationContext, request: $crate::GetRoleRequest) -> __LensoNativeSupportAccessControlDirectory::NativeRequestFuture<$crate::AccessControlDirectoryGetRole> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_role(&plugin, context, request).await;
                $crate::__LensoIntoAccessControlDirectoryGetRoleResult::__lenso_into_result(result)
            })
        }
        fn list_roles(&self, context: __LensoNativeSupportAccessControlDirectory::InvocationContext, request: $crate::ListRolesRequest) -> __LensoNativeSupportAccessControlDirectory::NativeRequestFuture<$crate::AccessControlDirectoryListRoles> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_roles(&plugin, context, request).await;
                $crate::__LensoIntoAccessControlDirectoryListRolesResult::__lenso_into_result(result)
            })
        }
        fn list_subject_roles(&self, context: __LensoNativeSupportAccessControlDirectory::InvocationContext, request: $crate::ListSubjectRolesRequest) -> __LensoNativeSupportAccessControlDirectory::NativeRequestFuture<$crate::AccessControlDirectoryListSubjectRoles> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_subject_roles(&plugin, context, request).await;
                $crate::__LensoIntoAccessControlDirectoryListSubjectRolesResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct AccessControlDirectoryRequestEndpoint { provider: Rc<dyn AccessControlDirectoryProvider> }

#[derive(Debug)]
pub struct AccessControlDirectoryEndpoint<P: AccessControlDirectoryProvider> { provider: Rc<P>, request_endpoint: AccessControlDirectoryRequestEndpoint }
impl<P: AccessControlDirectoryProvider> AccessControlDirectoryEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn AccessControlDirectoryProvider> = provider.clone();
        Self { provider, request_endpoint: AccessControlDirectoryRequestEndpoint { provider: request_provider } }
    }
}

impl<P: AccessControlDirectoryProvider> NativeRequestEndpoint for AccessControlDirectoryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        GET_ROLE_OPERATION,
        LIST_ROLES_OPERATION,
        LIST_SUBJECT_ROLES_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            GET_ROLE_OPERATION => {
                let Ok(request) = request.downcast::<GetRoleRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_role(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_ROLES_OPERATION => {
                let Ok(request) = request.downcast::<ListRolesRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_roles(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_SUBJECT_ROLES_OPERATION => {
                let Ok(request) = request.downcast::<ListSubjectRolesRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_subject_roles(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_access_control_directory {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::AccessControlDirectoryEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_access_control_directory {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_access_control_directory!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct AccessControlDirectoryClient {
    get_role: NativeRequestHandle<AccessControlDirectoryGetRole>,
    list_roles: NativeRequestHandle<AccessControlDirectoryListRoles>,
    list_subject_roles: NativeRequestHandle<AccessControlDirectoryListSubjectRoles>,
}
impl AccessControlDirectoryClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn get_role(&self, request: GetRoleRequest) -> Result<GetRoleResponse, AccessControlDirectoryGetRoleInvocationError> {
        self.get_role.invoke(GET_ROLE_OPERATION, request).await
            .map_err(AccessControlDirectoryGetRoleInvocationError::Runtime)?
            .map_err(AccessControlDirectoryGetRoleInvocationError::Domain)
    }

    pub async fn get_role_with_context(&self, context: InvocationContext, request: GetRoleRequest) -> Result<GetRoleResponse, AccessControlDirectoryGetRoleInvocationError> {
        self.get_role.invoke_with_context(GET_ROLE_OPERATION, context, request).await
            .map_err(AccessControlDirectoryGetRoleInvocationError::Runtime)?
            .map_err(AccessControlDirectoryGetRoleInvocationError::Domain)
    }

    pub async fn list_roles(&self, request: ListRolesRequest) -> Result<ListRolesResponse, AccessControlDirectoryListRolesInvocationError> {
        self.list_roles.invoke(LIST_ROLES_OPERATION, request).await
            .map_err(AccessControlDirectoryListRolesInvocationError::Runtime)?
            .map_err(AccessControlDirectoryListRolesInvocationError::Domain)
    }

    pub async fn list_roles_with_context(&self, context: InvocationContext, request: ListRolesRequest) -> Result<ListRolesResponse, AccessControlDirectoryListRolesInvocationError> {
        self.list_roles.invoke_with_context(LIST_ROLES_OPERATION, context, request).await
            .map_err(AccessControlDirectoryListRolesInvocationError::Runtime)?
            .map_err(AccessControlDirectoryListRolesInvocationError::Domain)
    }

    pub async fn list_subject_roles(&self, request: ListSubjectRolesRequest) -> Result<ListSubjectRolesResponse, AccessControlDirectoryListSubjectRolesInvocationError> {
        self.list_subject_roles.invoke(LIST_SUBJECT_ROLES_OPERATION, request).await
            .map_err(AccessControlDirectoryListSubjectRolesInvocationError::Runtime)?
            .map_err(AccessControlDirectoryListSubjectRolesInvocationError::Domain)
    }

    pub async fn list_subject_roles_with_context(&self, context: InvocationContext, request: ListSubjectRolesRequest) -> Result<ListSubjectRolesResponse, AccessControlDirectoryListSubjectRolesInvocationError> {
        self.list_subject_roles.invoke_with_context(LIST_SUBJECT_ROLES_OPERATION, context, request).await
            .map_err(AccessControlDirectoryListSubjectRolesInvocationError::Runtime)?
            .map_err(AccessControlDirectoryListSubjectRolesInvocationError::Domain)
    }
}

impl CapabilityClient for AccessControlDirectoryClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            get_role: dependencies.one::<AccessControlDirectoryGetRole>()?,
            list_roles: dependencies.one::<AccessControlDirectoryListRoles>()?,
            list_subject_roles: dependencies.one::<AccessControlDirectoryListSubjectRoles>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for AccessControlDirectoryClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    get_role: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccessControlDirectoryGetRole>()?,
                    list_roles: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccessControlDirectoryListRoles>()?,
                    list_subject_roles: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AccessControlDirectoryListSubjectRoles>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum AccessControlDirectoryGetRoleInvocationError {
    Domain(GetRoleError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AccessControlDirectoryListRolesInvocationError {
    Domain(ListRolesError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AccessControlDirectoryListSubjectRolesInvocationError {
    Domain(ListSubjectRolesError),
    Runtime(RuntimeFailure),
}
