#!/usr/bin/env python3
"""Generate immutable SQL byte boundaries using SQLite's statement parser."""
import argparse
import sqlite3
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
root = Path(__file__).resolve().parent.parent
owner = root / "crates/lenso-access-control-d1-plugin"
sql = (owner / "migrations/d1/001_create_access_control.sql").read_text()
ends = []
start = 0
for index, char in enumerate(sql):
    if char == ";" and sqlite3.complete_statement(sql[start:index + 1]):
        ends.append(len(sql[:index + 1].encode()))
        start = index + 1
if not ends or sql[start:].strip():
    raise SystemExit("incomplete SQL migration")
ends[-1] = len(sql.encode())
expected = "// @generated by scripts/generate-d1-migrations.py; do not edit.\n&[" + ", ".join(map(str, ends)) + "]\n"
output = owner / "src/migration_statement_ends.rs"
if args.check:
    if output.read_text() != expected:
        raise SystemExit("stale D1 statement boundaries")
else:
    output.write_text(expected)
